name: Build and Test
on: [push]
jobs:
  build_and_test:
    - name: Install Go
      uses: actions/setup-go@v2
      with: 
        go-version: '1.16'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      uses: go test ./...
    - name: Test
      uses: go build cmd/api-test-golang/main.go
    

